main:
  - name: "主页"
    identifier: "主页"
    weight: 100
    url: "/"

  - name: "标签"
    weight: 200
    identifier: "标签"
    url: "/tags/"

  - name: "文案"
    weight: 300
    identifier: "文案"
    url: "/articles/"

  - name: "脚本"
    weight: 400
    identifier: "脚本"
    url: "/scripts/"

  - name: "视频"
    weight: 500
    identifier: "视频"
    url: "/videos/"

  - name: "图片"
    weight: 600
    identifier: "图片"
    url: "/images/"

  - name: "关于我"
    weight: 700
    identifier: "关于我"
    url: "/about/"

#footer:
#  name: "imprint"
#  weight: 1
#  identifier: "imprint"
#  url: "/imprint/"